# Generated by Django 3.0.6 on 2020-05-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Architecture', models.TextField(blank=True, null=True)),
                ('Boost_Clock', models.IntegerField(blank=True, null=True)),
                ('Core_Speed', models.IntegerField(blank=True, null=True)),
                ('Memory', models.IntegerField(blank=True, null=True)),
                ('Memory_Speed', models.CharField(blank=True, max_length=20, null=True)),
                ('Memory_Bandwidth', models.CharField(blank=True, max_length=20, null=True)),
                ('DVI_Connection', models.CharField(blank=True, max_length=20, null=True)),
                ('Dedicated', models.CharField(blank=True, max_length=20, null=True)),
                ('Direct_X', models.CharField(blank=True, max_length=20, null=True)),
                ('HDMI_Connection', models.CharField(blank=True, max_length=20, null=True)),
                ('Integrated', models.CharField(blank=True, max_length=20, null=True)),
                ('L2_Cache', models.CharField(blank=True, max_length=20, null=True)),
                ('Manufacturer', models.CharField(blank=True, max_length=20, null=True)),
                ('Max_Power', models.CharField(blank=True, max_length=20, null=True)),
                ('Memory_Bus', models.CharField(blank=True, max_length=20, null=True)),
                ('Memory_Type', models.CharField(blank=True, max_length=20, null=True)),
                ('Power_Connector', models.TextField(blank=True, null=True)),
                ('Process', models.CharField(blank=True, max_length=20, null=True)),
                ('Resolution_WxH', models.CharField(blank=True, max_length=20, null=True)),
                ('SLI_Crossfire', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('url_name', models.TextField(blank=True, null=True)),
                ('img_of_gpu', models.ImageField(blank=True, null=True, upload_to='pics')),
            ],
        ),
    ]
